// Generated by Wrangler by running `wrangler types`

interface Env {
	WORKFLOW_KV: KVNamespace;
	XSTATE_DO: DurableObjectNamespace<import("./src/index").WebSocketDO>;
	XSTATE_WORKFLOW_JOBS: Queue;
	XSTATE_WORKFLOW: Workflow;
}
